development:
  adapter: mysql
  encoding: utf8
  database: perwikity_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  encoding: utf8
  database: perwikity_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  encoding: utf8
  database: perwikity_production
  pool: 5
  username: root
  password: 
  socket: /tmp/mysql.sock
